---
- include_role:
    name: "k3s"

- include_role:
    name: dt-operator
  vars:
    operator_mode: "classicFullStack"

- include_role:
    name: app-unguard

- include_role:
    name: app-easytrade

- include_role:
    name: dashboard
